/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sample;

import NSOCR.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.Thread;

/**
 *
 * @author Now
 */
public class dlgWait extends javax.swing.JDialog implements ActionListener  {
    
    public int  mode = 0;
    public HIMG ImgObj;
    public int  res;
    javax.swing.Timer timer;
    
    private boolean CheckDone()
    {
        if (mode == 0)
            res = NSOCR.Engine.Img_OCR(ImgObj, 0, 0, NSOCR.Constant.OCRFLAG_GETRESULT);
	else
        {
            HSVR svr = new HSVR();
            svr.Value = 0;
            
            res = NSOCR.Engine.Ocr_ProcessPages(ImgObj, svr, 0, 0, 0, NSOCR.Constant.OCRFLAG_GETRESULT);
        }
	return res !=  NSOCR.Error.ERROR_PENDING;        
    }
    
    private void OnOK()
    {
	timer.stop();

	while (!CheckDone()) //make sure that Img_OCR is done
        {
            try {
                    Thread.sleep(10);
                } 
            catch (InterruptedException e) 
                {                    
                    e.printStackTrace();
                }                        
        }	
            
        
        this.dispose();
    }
    
    @Override
    public void actionPerformed(ActionEvent e) 
    {
        int val;
                
        if (CheckDone()) OnOK();

        if (mode == 0)
        {
            val = NSOCR.Engine.Img_OCR(ImgObj, 0, 0, NSOCR.Constant.OCRFLAG_GETPROGRESS);
        }
        else
        {
            HSVR svr = new HSVR();
            svr.Value = 0;
            
            val = NSOCR.Engine.Ocr_ProcessPages(ImgObj, svr, 0, 0, 0, NSOCR.Constant.OCRFLAG_GETPROGRESS);
        }

        if (val < NSOCR.Error.ERROR_FIRST)
        {
	  if (ProgressBar.getValue() != val)
            ProgressBar.setValue(val);
        }  
    }    
    
    /**
     * Creates new form dlgWait
     */
    public dlgWait(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void init(HIMG ImgObj, int mode)
    {
        this.mode   = mode;
        this.ImgObj = ImgObj;
        
        ProgressBar.setMaximum(0);
        ProgressBar.setMaximum(100);
        ProgressBar.setValue(0);
                
        timer = new javax.swing.Timer(100, this);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Progress...");
        setResizable(false);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Please Wait");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(btnCancel)))
                        .addGap(0, 268, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //cancel work
	if (mode == 0)
            NSOCR.Engine.Img_OCR(ImgObj, 0, 0, NSOCR.Constant.OCRFLAG_CANCEL);
	else
            NSOCR.Engine.Ocr_ProcessPages(ImgObj, null, 0, 0, 0, NSOCR.Constant.OCRFLAG_CANCEL);

	//we must wait for result anyway since OCRFLAG_CANCEL request returns immediately, work is not stopped yet
	OnOK(); //this function waits for result
        
    }//GEN-LAST:event_btnCancelActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
