/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sample;
import  NSOCR.*;
import  javax.swing.*;
import  java.util.*;

/**
 *
 * @author Now
 */
public class Scan extends javax.swing.JDialog {

    private HSCAN ScanObj;
    private HIMG  ImgObj;
    public  boolean isOk   = false;
    public  boolean EnumOK = true;
    
    /**
     * Creates new form Scan
     */
    public Scan(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
    }
    
    public void Init(HSCAN ScanObj, HIMG ImgObj)
    {
        this.ScanObj = ScanObj;
        this.ImgObj  = ImgObj;
        
        cbSource.setSelectedIndex(0);
	cbDevice.removeAllItems();

	int res;
        
        StringBuffer ScannerName = new StringBuffer();

	res =  NSOCR.Engine.Scan_Enumerate(ScanObj, ScannerName, 0);
        
	if (res > NSOCR.Error.ERROR_FIRST)
	{
                EnumOK = false;
		JOptionPane.showMessageDialog(this, "Scan_Enumerate" + res);
		return;
	}

//names are separated by comma, parse them
        StringTokenizer tokenizer = new StringTokenizer(ScannerName.toString(), ",");                
	while (tokenizer.hasMoreElements())
	{
            cbDevice.addItem(tokenizer.nextToken());
	}

//now get default device index
	res = NSOCR.Engine.Scan_Enumerate(ScanObj, null, NSOCR.Constant.SCAN_GETDEFAULTDEVICE);
	if (res > NSOCR.Error.ERROR_FIRST)
	{
		if (res != NSOCR.Error.ERROR_NODEFAULTDEVICE)
		{
                        EnumOK = false;
                        JOptionPane.showMessageDialog(this, "Scan_Enumerate (1)" + res);
			return;
		}
	}
	else
	{
		if (res < cbDevice.getItemCount()) cbDevice.getSelectedIndex();
	}        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbDevice = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbSource = new javax.swing.JComboBox();
        cbNoUI = new javax.swing.JCheckBox();
        btScan = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Select Device:");

        cbDevice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Set as Deault");
        jButton1.addActionListener(formListener);

        jLabel2.setText("Document Source:");

        cbSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flatbed", "ADF (Automatic Document Feeder)", "Auto" }));

        cbNoUI.setText("No Scanner UI");

        btScan.setText("Scan");
        btScan.addActionListener(formListener);

        btCancel.setText("Cancel");
        btCancel.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbNoUI))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btScan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(cbNoUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btScan)
                    .addComponent(btCancel))
                .addGap(27, 27, 27))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jButton1) {
                Scan.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == btCancel) {
                Scan.this.btCancelActionPerformed(evt);
            }
            else if (evt.getSource() == btScan) {
                Scan.this.btScanActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	
	int n = cbDevice.getSelectedIndex();
	if (n < 0) return;

	int res = NSOCR.Engine.Scan_Enumerate(ScanObj, null, NSOCR.Constant.SCAN_SETDEFAULTDEVICE | n);
        
	if (res > NSOCR.Error.ERROR_FIRST)
	{
		JOptionPane.showMessageDialog(this, "Scan_Enumerate (2)"+res);
	}    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
       this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btScanActionPerformed
	int n, flags, res;
	n = cbDevice.getSelectedIndex();
        
	if (n < 0)
	{
		JOptionPane.showMessageDialog(this, "No scanner selected!");
		return;
	}

	flags = 0;
	switch (cbSource.getSelectedIndex())
	{
            case 0: break; //flatbed
            case 1: flags = flags | NSOCR.Constant.SCAN_SOURCEADF; break; //adf
            case 2: flags = flags | NSOCR.Constant.SCAN_SOURCEAUTO; break; //auto
	}

	if (cbNoUI.isSelected())
            flags = flags | NSOCR.Constant.SCAN_NOUI;

	res = NSOCR.Engine.Scan_ScanToImg(ScanObj, ImgObj, n, flags);
	
	if (res > NSOCR.Error.ERROR_FIRST)
	{
		JOptionPane.showMessageDialog(this, "Scan_ScanToImg" + res);
		return;
	}
        
        this.dispose();
        isOk = true;
    }//GEN-LAST:event_btScanActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btCancel;
    javax.swing.JButton btScan;
    javax.swing.JComboBox cbDevice;
    javax.swing.JCheckBox cbNoUI;
    javax.swing.JComboBox cbSource;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
