/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NSOCR_Engine */

#ifndef _Included_NSOCR_Engine
#define _Included_NSOCR_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NSOCR_Engine
 * Method:    IsDllLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_NSOCR_Engine_IsDllLoaded
  (JNIEnv *, jclass);

/*
 * Class:     NSOCR_Engine
 * Method:    Engine_GetVersion
 * Signature: (Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Engine_1GetVersion
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Engine_Initialize
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Engine_1Initialize(JNIEnv *, jclass);

/*
 * Class:     NSOCR_Engine
 * Method:    Engine_InitializeAdvanced
 * Signature: (LNSOCR/HCFG;LNSOCR/HOCR;LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Engine_1InitializeAdvanced(JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Engine_Uninitialize
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Engine_1Uninitialize(JNIEnv *env, jclass self);

//-----------------------------------------------------------------------------
/*
 * Class:     NSOCR_Engine
 * Method:    Engine_SetDataDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Engine_1SetDataDirectory(JNIEnv *env, jclass self, jstring directory);

//-----------------------------------------------------------------------------
/*
 * Class:     NSOCR_Engine
 * Method:    Engine_SetDataDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Engine_1SetLicenseKey(JNIEnv *env, jclass self, jstring licensekey);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_Create
 * Signature: (LNSOCR/HCFG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1Create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_Destroy
 * Signature: (LNSOCR/HCFG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1Destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_LoadOptions
 * Signature: (LNSOCR/HCFG;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1LoadOptions
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_SaveOptions
 * Signature: (LNSOCR/HCFG;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1SaveOptions
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_GetOption
 * Signature: (LNSOCR/HCFG;ILjava/lang/String;Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1GetOption
  (JNIEnv *, jclass, jobject, jint, jstring, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_SetOption
 * Signature: (LNSOCR/HCFG;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1SetOption
  (JNIEnv *, jclass, jobject, jint, jstring, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_DeleteOption
 * Signature: (LNSOCR/HCFG;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1DeleteOption
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_LoadOptionsFromString
 * Signature: (LNSOCR/HCFG;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1LoadOptionsFromString
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Cfg_SaveOptionsToString
 * Signature: (LNSOCR/HCFG;Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Cfg_1SaveOptionsToString
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Ocr_Create
 * Signature: (LNSOCR/HCFG;LNSOCR/HOCR;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Ocr_1Create
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Ocr_Destroy
 * Signature: (LNSOCR/HOCR;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Ocr_1Destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Ocr_ProcessPages
 * Signature: (LNSOCR/HIMG;LNSOCR/HSVR;IIII)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Ocr_1ProcessPages
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_Create
 * Signature: (LNSOCR/HOCR;LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1Create
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_Destroy
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1Destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_LoadFile
 * Signature: (LNSOCR/HIMG;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1LoadFile
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_LoadFromMemory
 * Signature: (LNSOCR/HIMG;[BI)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1LoadFromMemory
  (JNIEnv *, jclass, jobject, jbyteArray, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_LoadBmpData
 * Signature: (LNSOCR/HIMG;[IIII)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1LoadBmpData
  (JNIEnv *, jclass, jobject, jintArray, jint, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_Unload
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1Unload
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetPageCount
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetPageCount
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_SetPage
 * Signature: (LNSOCR/HIMG;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1SetPage
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetSize
 * Signature: (LNSOCR/HIMG;LNSOCR/NSInt;LNSOCR/NSInt;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetSize
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetBmpData
 * Signature: (LNSOCR/HIMG;[ILNSOCR/NSInt;LNSOCR/NSInt;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetBmpData
  (JNIEnv *, jclass, jobject, jintArray, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_DeleteAllBlocks
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1DeleteAllBlocks
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_AddBlock
 * Signature: (LNSOCR/HIMG;IIIILNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1AddBlock
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_DeleteBlock
 * Signature: (LNSOCR/HIMG;LNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1DeleteBlock
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetBlockCnt
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetBlockCnt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetBlock
 * Signature: (LNSOCR/HIMG;ILNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetBlock
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetImgText
 * Signature: (LNSOCR/HIMG;Ljava/lang/StringBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetImgText
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_OCR
 * Signature: (LNSOCR/HIMG;III)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1OCR
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_LoadBlocks
 * Signature: (LNSOCR/HIMG;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1LoadBlocks
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_SaveBlocks
 * Signature: (LNSOCR/HIMG;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1SaveBlocks
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetSkewAngle
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetSkewAngle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetPixLineCnt
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetPixLineCnt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetPixLine
 * Signature: (LNSOCR/HIMG;ILNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetPixLine
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetScaleFactor
 * Signature: (LNSOCR/HIMG;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetScaleFactor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_CalcPointPosition
 * Signature: (LNSOCR/HIMG;LNSOCR/NSInt;LNSOCR/NSInt;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1CalcPointPosition
  (JNIEnv *, jclass, jobject, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_CopyCurrentPage
 * Signature: (LNSOCR/HIMG;LNSOCR/HIMG;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1CopyCurrentPage
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_GetProperty
 * Signature: (LNSOCR/HIMG;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1GetProperty
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_SaveToFile
 * Signature: (LNSOCR/HIMG;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1SaveToFile
  (JNIEnv *, jclass, jobject, jstring, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Img_SaveToMemory
 * Signature: (LNSOCR/HIMG;[BII)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Img_1SaveToMemory
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetType
 * Signature: (LNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_SetType
 * Signature: (LNSOCR/HBLK;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1SetType
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetRect
 * Signature: (LNSOCR/HBLK;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetRect
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetText
 * Signature: (LNSOCR/HBLK;Ljava/lang/StringBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetText
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetLineCnt
 * Signature: (LNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetLineCnt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetLineText
 * Signature: (LNSOCR/HBLK;ILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetLineText
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetWordCnt
 * Signature: (LNSOCR/HBLK;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetWordCnt
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetWordText
 * Signature: (LNSOCR/HBLK;IILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetWordText
  (JNIEnv *, jclass, jobject, jint, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_SetWordText
 * Signature: (LNSOCR/HBLK;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1SetWordText
  (JNIEnv *, jclass, jobject, jint, jint, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetCharCnt
 * Signature: (LNSOCR/HBLK;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetCharCnt
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetCharRect
 * Signature: (LNSOCR/HBLK;IIILNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetCharRect
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetCharText
 * Signature: (LNSOCR/HBLK;IIIILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetCharText
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetCharQual
 * Signature: (LNSOCR/HBLK;IIII)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetCharQual
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetTextRect
 * Signature: (LNSOCR/HBLK;IILNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetTextRect
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_Inversion
 * Signature: (LNSOCR/HBLK;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1Inversion
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_Rotation
 * Signature: (LNSOCR/HBLK;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1Rotation
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_Mirror
 * Signature: (LNSOCR/HBLK;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1Mirror
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_IsWordInDictionary
 * Signature: (LNSOCR/HBLK;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1IsWordInDictionary
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_SetRect
 * Signature: (LNSOCR/HBLK;IIII)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1SetRect
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetWordQual
 * Signature: (LNSOCR/HBLK;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetWordQual
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetWordFontColor
 * Signature: (LNSOCR/HBLK;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetWordFontColor
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetWordFontSize
 * Signature: (LNSOCR/HBLK;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetWordFontSize
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetWordFontStyle
 * Signature: (LNSOCR/HBLK;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetWordFontStyle
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetBackgroundColor
 * Signature: (LNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetBackgroundColor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_SetWordRegEx
 * Signature: (LNSOCR/HBLK;IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1SetWordRegEx
  (JNIEnv *, jclass, jobject, jint, jint, jstring, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetBarcodeCnt
 * Signature: (LNSOCR/HBLK;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetBarcodeCnt
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetBarcodeText
 * Signature: (LNSOCR/HBLK;ILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetBarcodeText
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetBarcodeRect
 * Signature: (LNSOCR/HBLK;ILNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;LNSOCR/NSInt;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetBarcodeRect
  (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Blk_GetBarcodeType
 * Signature: (LNSOCR/HBLK;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Blk_1GetBarcodeType
  (JNIEnv *, jclass, jobject, jint);


/*
 * Class:     NSOCR_Engine
 * Method:    Svr_Create
 * Signature: (LNSOCR/HCFG;ILNSOCR/HSVR;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1Create
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_Destroy
 * Signature: (LNSOCR/HSVR;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1Destroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_NewDocument
 * Signature: (LNSOCR/HSVR;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1NewDocument
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_AddPage
 * Signature: (LNSOCR/HSVR;LNSOCR/HIMG;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1AddPage
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_SaveToFile
 * Signature: (LNSOCR/HSVR;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1SaveToFile
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_SaveToMemory
 * Signature: (LNSOCR/HSVR;[B)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1SaveToMemory
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_GetText
 * Signature: (LNSOCR/HSVR;ILjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1GetText
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Svr_SetDocumentInfo
 * Signature: (LNSOCR/HSVR;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Svr_1SetDocumentInfo
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     NSOCR_Engine
 * Method:    Scan_Create
 * Signature: (LNSOCR/HCFG;LNSOCR/HSCAN;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Scan_1Create
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NSOCR_Engine
 * Method:    Scan_Enumerate
 * Signature: (LNSOCR/HSCAN;Ljava/lang/StringBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Scan_1Enumerate
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Scan_ScanToImg
 * Signature: (LNSOCR/HSCAN;LNSOCR/HIMG;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Scan_1ScanToImg
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Scan_ScanToFile
 * Signature: (LNSOCR/HSCAN;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Scan_1ScanToFile
  (JNIEnv *, jclass, jobject, jstring, jint, jint);

/*
 * Class:     NSOCR_Engine
 * Method:    Scan_Destroy
 * Signature: (LNSOCR/HSCAN;)I
 */
JNIEXPORT jint JNICALL Java_NSOCR_Engine_Scan_1Destroy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
